version: '3.8'

services:
  app:
    build: .
    container_name: order-management-app
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order_management
      - DB_SSL=false
      - USE_NEW_SCHEMA=true
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION=24h
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: sh -c "npm run migrate-and-dev"

  postgres:
    image: postgres:14-alpine
    container_name: order-management-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./client
    container_name: order-management-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - app
    restart: unless-stopped
    stdin_open: true
    command: npm start

volumes:
  postgres_data:
