{
 "title": "Order Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Запити до сервісу замовлень за методом (запитів/сек)",
   "type": "timeseries",
   "description": "Загальна кількість запитів до сервісу замовлень",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=\"order-service\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Середній час відповіді за маршрутами (мс)",
   "type": "timeseries",
   "description": "Середній час відповіді для різних маршрутів сервісу замовлень",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_sum{service=\"order-service\"}[5m]) / rate(http_request_duration_ms_count{service=\"order-service\"}[5m]) * 1000",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Запити до сервісу замовлень за статус-кодом",
   "type": "piechart",
   "description": "Кількість замовлень за статусом",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{service=\"order-service\", route=~\"/api/orders.*\"}) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}